In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


# Applied Matrices

## Crafting example

This is an example that utilizes crafting with matrices.

**Items**

* Iron Ore
* Iron Plate
* Iron Gear
* Copper Ore
* Copper Plate
* Copper Wire
* Inserter

**Resources**

* Iron: ore $\xrightarrow{\text{2}}$ plate $\xrightarrow{\text{1}}$ gear
* Copper: ore $\xrightarrow{\text{2}}$ plate $\xrightarrow{\text{1}}$ wire

**Items**

* Copper wire 3
  * 1 Copper plate 
* Inserter
  * 2 Copper wire
  * 1 Iron gear
  * 1 Iron plate

### Item Matrix

We need an item matrix with all the item types.

In [89]:
# Amount matrix
P = np.matrix([[0,0,0,0],[2,0,0,0],[0,2,0,0],[0,2,1,0]])

In [90]:
P

matrix([[0, 0, 0, 0],
        [2, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 2, 1, 0]])

In [91]:
E = np.zeros(16).reshape((4,4))
np.fill_diagonal(E,1)

In [92]:
E

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [99]:
EPInv = np.linalg.inv(E-P)

In [120]:
A = np.array([0,0,0,1])
Ar = np.reshape(A, (4,1))

In [121]:
Ar

array([[0],
       [0],
       [0],
       [1]])

In [124]:
i1 = (E-P).T*Ar

In [125]:
i2 = i1 - Ar

In [126]:
i2

matrix([[ 0.],
        [-2.],
        [-1.],
        [ 0.]])

In [127]:
i3 = (E-P).T*i2

In [128]:
i3

matrix([[ 4.],
        [ 0.],
        [-1.],
        [ 0.]])

http://optimierung.mathematik.uni-kl.de/mamaeusch/veroeffentlichungen/ver_texte/stuecklisten_english.pdf